name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres:11
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: Set up Rails
      run: |
        sudo apt-get -yqq install libpq-dev
        bundle install --jobs 4 --retry 3
    - name: Set up DB
      env:
        RAILS_ENV: test
      run: |
        sudo systemctl start postgresql
        cat /var/run/postgresql/.s.PGSQL.5432
        bin/rails db:prepare
    - name: Run tests
      run: bundle exec rspec ./spec
