name: Static Code Analysis
on: [push, pull_request]
jobs:
  SonarScanner:
    runs-on: ubuntu-latest
    name: Sonar Scanner
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Scan code
        uses: vtex/action-sonarqube@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          host: ${{ secrets.SONARQUBE_HOST }}
          token: ${{ secrets.SONARQUBE_TOKEN }}
